### ISSUE TITLE
Android channel's not being created

### ISSUE THREAD

**Issue by PovilasID** [SgtBatten/HA_blueprints#1]
Problem: 
I specified channel in the field 'Notification Channel - Android only (Optional)' and on my phone I get notifications that belong to 'General' Channel.

Expected behaviour:
After first notification in OS notification setting to see a new channel appear.

Additional information:
I created a simple clean automation to with only notification action and set it's `data` field to `channel: test` and ran the action. To validate that the app and the phone is working as intended. They do. A new channel appeared.

Version:
Script: 0.11.0.15
Phone: Android 11
HA: 2023.4.0

P.S. Thanks a lot for curating all those snippets! This and awesome resource.

**Comment by SgtBatten** [comment]
I made an error with that versions upload. It does not support channels despite the inputs being there. 

Only the beta currently supports channels but with next stable release expect it to support channels.

**Comment by PovilasID** [comment]
Can confirm that channels works with beta
