### ISSUE TITLE
[Config Support]: Possible to leverage Blueprint for Double Take Facial Rec?

### ISSUE THREAD

**Issue by superdong69** [SgtBatten/HA_blueprints#108]
### Describe the problem you are having or the outcome you are trying to achieve.

I'm trying to utilize the person blueprints to only alert if double take says the person is "Unknown", meaning not trained in my system. I'd like the notifications to not trigger when I'm walking around the house. Is this possible?

### Version

0.11

### Automation config file

```yaml
NA
```

### Frigate Config

```yaml
NA
```

**Comment by SgtBatten** [comment]
I don't think double take updates frigate with unknown does it? you'd have to make your own template to capture it if that's the case.

**Comment by bozzio83** [comment]
How do i add known people? This is what I currently have but no luck.
```use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.frontdoor
    notify_device: ec1235dda196d323e5476b48f3009568
    critical: "true"
    attachment: snapshot
    message: >-
      {{ label }} {{'is loitering' if loitering else 'was detected'}} on the {{
      frontdoor }} camera.```

**Comment by SgtBatten** [comment]
> How do i add known people? This is what I currently have but no luck.

![image](https://github.com/SgtBatten/HA_blueprints/assets/24822223/51c3b746-de15-4c53-9a4b-eba5a52fddcf)
You need the beta
