### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by torsteinelv** [SgtBatten/HA_blueprints#111]
### Describe the problem you are having or the outcome you are trying to achieve.

we have to option to ignore notification if presence is home. But at night time we can get notifications ex from 22:00 to 09:00?

### Version

0.12.0.1

### Automation config file

```yaml
NA
```

**Comment by torsteinelv** [comment]
And also. when presence is maid available. we can wait ex 2 minutes before sending notification and see if presence is detected?

**Comment by SgtBatten** [comment]
In the beta there is an option to create a custom filter. You can use this to create a presence filter that only applies during the day. 

Alternatively make two automations, one with a presence filter and one with a time filter.

Off the top of my head I can't think of a good way to resolve your second message sorry
