### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by augster** [SgtBatten/HA_blueprints#113]
**Describe what you are trying to accomplish and why in non technical terms**
I'm submitting this as a feature request rather than bug because I'm unsure of what the original intent of the Notification Cooldown setting was for. So here is what I'd like added, or perhaps fixed/changed:
I would like the notification cooldown time to work based on the time the last notification was sent (not based on the time of the last event). So for example, based on my automations settings, I want to be notified anytime any object enters my "driveway" zone at any time throughout the day. I'd also like to not receive more than 1 of these notifications for every 5 minutes. Any motion/objects that are detected outside of the "driveway" zone are ignore and should NOT affect the cooldown time. Here is an example: 
1. a vehicle drives past my house at 8:59am and is seen on the camera but is NOT in the "driveway" zone -> I do not get a notification
2. a vehicle enters my "driveway" at 9:00am -> I get a notification
3. a vehicle drives past my house at 9:03am and is seen on the camera but is NOT in the "driveway" zone -> I do not get a notification
4. a person walks on my "driveway" at 9:03am -> I do not get a notification because it's been less than 5 minutes.
5. another vehicle enters my "driveway" at 9:06am -> I get another notification.

What is currently happening, is that the vehicle in #1 above is starting the cooldown timeout so I don't get notified about the vehicle in #2. I will only be notified when an object is in my "driveway" zone if there were no events at all 5 minutes prior. 

**Describe the solution you'd like**
I think the Notification Cooldown setting should be adjusted to match the above. I.e. time based on the last notification not the last event the automation received.

**Describe alternatives you've considered**
I've stopped using the cooldown because I'm constantly missing events because my automation is receiving events outside of my desired zone. I could perhaps accomplish the same thing by using the state entity filter. So when a notification is sent, a cooldown entity is enabled for 5 minutes. The automation would then halt any further notifications while this entity is enabled. I haven't tried this approach yet but I think I will.

**Comment by SgtBatten** [comment]
Yep great concept. No idea how to get that information off the top of my head. Hopefully it's achievable.

**Comment by SgtBatten** [comment]
Actually one idea. Use the custom action function in the beta to update a date time helper and then use that in the custom filter. That would work with the current beta blueprint I think.

**Comment by augster** [comment]
Thanks for the ideas. I was able to get this to work by using the your BETA blueprint, a timer helper, a custom action to start the timer, and an entity state filter that checks the timer status. So far it seems to be working exactly as I want! I never even thought of using the BETA, I didn't realize it had those custom actions, but that works perfectly!
