### ISSUE TITLE
[Config Support]: Automation not firing

### ISSUE THREAD

**Issue by Jealy91** [SgtBatten/HA_blueprints#116]
### Describe the problem you are having or the outcome you are trying to achieve.

Not sure where I'm going wrong here, pretty standard setup but the automation just isn't firing even though events are being created in Frigate.

I see frigate in MQTT explorer, have the integration set-up correctly.

### Version

0.12.0.2

**Comment by Jealy91** [comment]
Turns out you can't have underscores in your entity names, removed them and it worked perfectly.

Thanks for the awesome blueprint :)

**Comment by SgtBatten** [comment]
You can have underscores in your entity names. You can't have it end in _x where X is a number though. Based on your original post I suspect that is what occurred.

**Comment by Jealy91** [comment]
It was, thanks mate!

Already had entities with the same name and Home Assistant did its thing.

Thanks for the extra info.
