### ISSUE TITLE
[Feature Request]: To add check for the availability of TV notification

### ISSUE THREAD

**Issue by pephumin** [SgtBatten/HA_blueprints#123]
First of all thanks for the blueprint, I have been using it happily for several months.

But because I do not have my TV turned on at all time (android box is on/off controlled by a smart plug), so the script will give an error to home-assistant on unable to find such service (notify.tv in my case).

Below is the logs

```
Logger: homeassistant.components.automation.frigate_bb1
Source: helpers/script.py:1783
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 6:17:20 PM (8 occurrences)
Last logged: 6:38:23 PM

Frigate BB1: Choose at step 1: Frigate Event: Notify on new object: choice 1: Choose at step 1: choice 2: Error executing script. Service not found for call_service at pos 1: Unable to find service notify.tv
Frigate BB1: Choose at step 1: Frigate Event: Notify on new object: choice 1: Error executing script. Service not found for choose at pos 1: Unable to find service notify.tv
Frigate BB1: Choose at step 1: Frigate Event: Error executing script. Service not found for choose at pos 4: Unable to find service notify.tv
Frigate BB1: Error executing script. Service not found for choose at pos 1: Unable to find service notify.tv
```

It would be great if you can add a check for the availability of TV notification service to the blueprint before making a service call (else/when inot available, skip it)

Thanks in advanced.
Phumin

**Comment by SgtBatten** [comment]
You can use the state filter or custom filter.

**Comment by pephumin** [comment]
thank you.

**Comment by SgtBatten** [comment]
No problem. I have the same thing setup for the same reason. If the TV is offline it no longer tries to notify it.
