### ISSUE TITLE
[Feature Request]: Notification to Group (members) only when ..

### ISSUE THREAD

**Issue by micAThome** [SgtBatten/HA_blueprints#125]
What I would need is that case:

1. 2 (or more) persons (and therefore devices) are living in the house
2. send a notification only to all when all are **out of the house** or in defined locations
3. send a notfication only to that persons (devices) of that group, which are not at home (or defined location[s])

Currently only one (1) mobile device can be defined OR /AND a group (with many mobile devices).

Maybe I do not understand the "rules" in the config and this could be already achieved ?

**Comment by SgtBatten** [comment]
I don't think this is worth the effort. If you want to try I'm happy to review but I do not have time to look into this. 

Simply set up multiple automations with appropriate presence rules to achieve this outcome.

**Comment by micAThome** [comment]
Okay, because HA is new to me, I was not aware that the same blueprint can be used for several - different - actions.

**Comment by SgtBatten** [comment]
Perhaps it could indeed be more efficient in the future but it would require reworking a fair bit of the logical flow I think. 

Yep you can use a blueprint as many times as you want. I think I have about 14 of this one going at various times.
