### ISSUE TITLE
[Feature Request]: Support Telegram notifications

### ISSUE THREAD

**Issue by borgqueenx** [SgtBatten/HA_blueprints#139]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to get notifications in telegram. there is a blueprint out there for telegram, but zones are not working in it. Your script also offers more customalization, such as sending a link to the clip file thats locally stored.

**Describe the solution you'd like**
Supporting a easy way to implement telegram notifications.

**Describe alternatives you've considered**
Blueprints, but only found one, and zones are broken in it. 
Nick's script, but proved too hard for me to convert it to telegram, just like your script.

**Additional context**
None, thanks for reading and happy holidays :)

**Comment by SgtBatten** [comment]
Please try #38 which has stalled due to lack of testers. 

Also share details of the working telegram blueprint. Provide any yaml comparisons you can to assist me get it working better.

**Comment by SgtBatten** [comment]
closed by #315
