### ISSUE TITLE
[Bug]: Stable is tagged as v0.12.0.1 but has internal version of 0.11.0.17

### ISSUE THREAD

**Issue by tykeal** [SgtBatten/HA_blueprints#16]
### Description

I saw a release announcement for 0.12.0.1 and went to install the updated version and was greeted with the description stating it version 0.11.0.17.

### Version

Stable (0.12.0.1 or 0.11.0.17???)

### Automation Config

```yaml
N/A - I didn't finish importing and it isn't broken
```

**Comment by SgtBatten** [comment]
Thanks, rereleased it now. just forgot to change it in the blueprint.
