### ISSUE TITLE
[Feature Request]: Add also sound triggering

### ISSUE THREAD

**Issue by jokerigno** [SgtBatten/HA_blueprints#161]
**Describe what you are trying to accomplish and why in non technical terms**
Frigate allwos also to fire event for sound event (scream, crying, speech etc)

**Describe the solution you'd like**
It would be great if also this sensor changes will trigger the automation (in my case babymonitoring)

**Describe alternatives you've considered**
Do the automation myself

**Additional context**
Here's the link describing the audio detection
https://docs.frigate.video/configuration/audio_detectors/

**Comment by stinobook** [comment]
Any updates on this?

**Comment by SgtBatten** [comment]
Very little time sorry. 

Does it send an MQTT message? Can you share an example message.

**Comment by stinobook** [comment]
I'd love to take a look on how to help you here but i can't figure out how the blueprint gets the events.

i did find this on frigate docs:

https://docs.frigate.video/integrations/mqtt#frigatecamera_nameaudioaudio_type

**Comment by SgtBatten** [comment]
Frigate publishes Mqtt messages with event data. We set up home assistant to monitor those messages and trigger the blueprint

**Comment by stinobook** [comment]
So following what i found on frigate docs, i setup a listener: 
![image](https://github.com/SgtBatten/HA_blueprints/assets/51697064/bf1b7f8d-8fd4-4497-b800-0159346489cd)

i also listened on frigate/events but never got anything i could make out of it that would indicate it was an audio event.

**Comment by jmadden91** [comment]
> Very little time sorry.
> 
> Does it send an MQTT message? Can you share an example message.

I'll try to grab a proper example message when I can, but I believe the endpoint is below. Eg a bark sound detected would be /frigate/<camera>/audio/bark "ON"

![image](https://github.com/SgtBatten/HA_blueprints/assets/30562276/48443acc-f93c-4da3-bbb3-1e3d6afb981c)

**Comment by jokerigno** [comment]
I confim.

This is my mqtt sensr that expose dB coming from the audio of the cam:

```
mqtt:
  sensor:
    - name: "Decibel Cameretta"
      state_topic: "frigate/__mycamera___/audio/dBFS"
      value_template: "{{ value | round(0) }}"
```

Based on this I create a binary sensor that becomes on if the noise is above a decibel level:

```
  - binary_sensor:
      - name: "Decibel higher that theshold for 2 secs"
        delay_on: 00:00:02
        delay_off: 00:00:05
        state: >
          {% if states('sensor.decibel_cameretta') < states('input_number.sensibilita_rumore_babymonitor') %}
          true
          {% else %}
          false
          {% endif %}
```

**Comment by stinobook** [comment]
> I confim.
> 
> This is my mqtt sensr that expose dB coming from the audio of the cam:
> 
> ```
> mqtt:
>   sensor:
>     - name: "Decibel Cameretta"
>       state_topic: "frigate/__mycamera___/audio/dBFS"
>       value_template: "{{ value | round(0) }}"
> ```
> 
> Based on this I create a binary sensor that becomes on if the noise is above a decibel level:
> 
> ```
>   - binary_sensor:
>       - name: "Decibel higher that theshold for 2 secs"
>         delay_on: 00:00:02
>         delay_off: 00:00:05
>         state: >
>           {% if states('sensor.decibel_cameretta') < states('input_number.sensibilita_rumore_babymonitor') %}
>           true
>           {% else %}
>           false
>           {% endif %}
> ```
> 
> This binary sensor trigger my babymonitor automation
> 
> NB: i switched from audio type to decibel because I found audio type not so reliable for my scope.

That is really smart! indeed i'd also prefer just to work with dB instead of the AI version :)

**Comment by SgtBatten** [comment]
The way the blueprint is setup currently relies very heavily on the mqqt event that frigat generates for object detection. I don;t see how i could implement this without essentiall duplicating the blueprint as much as i want to be able to.

**Comment by jokerigno** [comment]
> The way the blueprint is setup currently relies very heavily on the mqqt event that frigat generates for object detection. I don;t see how i could implement this without essentiall duplicating the blueprint as much as i want to be able to.

maybe creating another trigger that has same output? (i don't know it is how i would proceed with regual autoations)

**Comment by SgtBatten** [comment]
From what has been explained to me int his thread, it's not something feasible within the current blueprint.  If you took just the notification portion of the blueprint and made you own trigger and automation you could pretty much have what you want without any effort. It just isnt possible the way the blueprint it written now to incorporate it.

**Comment by jmadden91** [comment]
Fair enough, thanks mate. 
Would you be able to point me in the right direction to open the live stream of the camera when I click the notification? 
I also have frigate available at https://frigate.mydomain.com as well if that helps?

`alias: Dog Barking
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.side_gate_bark_sound
    to: "on"
condition: []
action:
  - service: notify.everyone
    data:
      message: It sounds like the dog is barking at the gate
      data:
        image: http://192.168.10.6:5000/api/Side_Gate/latest.jpg
mode: single`

**Comment by SgtBatten** [comment]
This is how the blueprint does it

```
"{{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'] | lower | replace('-','_')}}?token={{state_attr( 'camera.' ~ camera, 'access_token')}}"
```

If you ar ehard coding it into your own yaml it would be fairly easy

{{base_url}} is your home assistant url i.e https://homeassistant.mydomain.com
{{trigger.payload_json['after']['camera'] | lower | replace('-','_')}} = name of your camera i.e side_gate
{{state_attr( 'camera.' ~ camera, 'access_token')}} can be simplified to {{state_attr( 'camera.side_gate', 'access_token')}}

**Comment by stinobook** [comment]
Thanks for this ! @jokerigno @SgtBatten 

Doing what I need it to do! :D 
![image](https://github.com/SgtBatten/HA_blueprints/assets/51697064/5338b711-844f-4622-bc3c-9959b4309d76)
