### ISSUE TITLE
[Feature Request]: disabled days

### ISSUE THREAD

**Issue by MP-pi-ha** [SgtBatten/HA_blueprints#163]
**Describe what you are trying to accomplish and why in non technical terms**
I am attempting to limit push notification during particular times and days.
For example: Frigate sends an event when a person is detected, I would like to receive a push notification on an iPhone during all times except 16:00 - 18:00 on Tuesday's and Thursday's.

**Describe the solution you'd like**
I would like to have a disabled days selector when building an automation, just like the disabled times filter.

**Describe alternatives you've considered**
I attempted to make a copy of stable.yaml and add the functionality, but I am not very good with the logic and syntax to get it working correctly.

**Additional context**
This automation template absolutely rocks, I just wish it had a selector that can disable notification for certain time periods on particular days.

**Comment by SgtBatten** [comment]
In the beta we have a custom filter option. 

you could make a weekday sensor and use it in a template resulting inn True or False.

i'll leave this open as a future addition though.

**Comment by MP-pi-ha** [comment]
Sounds good, thank you for your help and advice I'll take a look at those options.
