### ISSUE TITLE
[Config Support]: Notification Channel - Android only (Optional)

### ISSUE THREAD

**Issue by mikoday** [SgtBatten/HA_blueprints#166]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello, I want to be alerted by my Android device as soon as possible but don't understand how to set this option:
```
Notification Channel - Android only (Optional)
Create a new channel for notifications to allow custom notification sounds, vibration patterns and override of Do Not Disturb mode. Configured directly on the device.
```
What should I do in my Android device after I type here the channel name?

### Version

0.12.0.3

### Automation config file

```yaml
...
```

**Comment by SgtBatten** [comment]
It's different on every device but once you receive a notification on that channel, you should be able to configure the channel somewhere deep in your notification settings.

**Comment by SgtBatten** [comment]
Actually it's in the home assistant companion app settings.
