### ISSUE TITLE
[Feature Request]: Notifications by zone?

### ISSUE THREAD

**Issue by PatSloan** [SgtBatten/HA_blueprints#170]
I'd like to see notifications by zones.   IE, I want to know when a car is on the driveway etc..  

The reason is, right now, my notifications are all sourced by the camera.  When I get a notification, I'd like to know what zone the detection is for.  Several of my cameras overlap.   For me, a person detected on driveway is different than a person detected at front door.  but the notifications from the driveway could be notifying a person at front of the door, but the notification does not give that info.  (unless i view the snap or video) .  I'd like to have that in the notification text.  

Possibly add {{ zone }} variable for the message?   or maybe have the notification events triggered by zone instead of only triggered by camera.

**Comment by SgtBatten** [comment]
The message can be customised with whatever you like, I only give some examples in the drop down. The long example includes zones in the message.

You can also filter by zones so notifications only get send if the object has been in the desired zone(s)

**Comment by PatSloan** [comment]
I did not see that documented anywhere.  Is there a list other then this?

Only variables listed are {{camera}} {{ event['after']['top_score'] |float(0) }} {{label}} {{event['before']['start_time']|timestamp_custom('%H:%M')}}


https://github.com/SgtBatten/HA_blueprints/blob/main/Frigate%20Camera%20Notifications/Guide%3A%20Configuration%20Options.md

<html><body>

Camera Name | {{camera}} | The formatted (friendly) name of the camera
-- | -- | --
Confidence | {{ event['after']['top_score'] \|float(0) }} | The value indicating the frigate confidence value
Object | {{label}} | The Object type - replaced by persons name if double take face match is correctly configured
Time | {{event['before']['start_time']\|timestamp_custom('%H:%M')}} | The event start time


</body>
</html>

**Comment by SgtBatten** [comment]
The documentation is missing 90%. I have not had time to finish it. 

Look through the actual blueprint and you will see dozens of variables all get generated at the beginning of the notification loop.

**Comment by PatSloan** [comment]
Thanks for the help.  I tried everything I could think of to get the zone name to display.   no go.

I tried:
{{ current_zone }}
{{ entered_zone }}
event['after']['zone']
event['after']['current_zone'] 
{{ event['after']['current_zone'] }}
{{ zone }}
{{ zone_name }}
{{ zones }}

etc..  etc...

**Comment by SgtBatten** [comment]
You were close. The answer is entered_zones for stable and enteredzones for beta. As i mentioned, the Long message once selected would have revealed this in the yaml. 

That being said I've just made some significant improvements to this in the beta.

**Comment by PatSloan** [comment]
thanks for clarifying.  I've tried using the long msg and I don't see the resulting zone included in the msg.   maybe I have something else going on   I do have an open issue with the has integration maybe some of my mqtt msg's are not getting transmitted fully or something like that?

https://github.com/blakeblackshear/frigate-hass-integration/issues/601

**Comment by SgtBatten** [comment]
I have seen cases where Mqtt messages aren't always triggering a loop, so not every single message is used. 

Try the beta if you aren't using it already.

**Comment by PatSloan** [comment]
beta with the long msg shows the event zone for me.   So that works :)   thanks.
