### ISSUE TITLE
[Feature Request]: ability to input sound volume

### ISSUE THREAD

**Issue by trowaflo** [SgtBatten/HA_blueprints#173]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to manage the sound volume of critical notifications on iOS.

Set the sound to 25% (because 100% in a silent context is quite annoying).
Have no sound, but still receive critical alerts, in silent mode.

**Describe alternatives you've considered**
I want to be able to select the 'none' sound option and really have no sound, cause now none is like default.

**Additional context**
I already made a PR. I run my version since this issue. 
refs: https://github.com/SgtBatten/HA_blueprints/pull/172

Please excuse in advance if the solutions I propose do not consider Android compatibility as I do not have any devices on which to test.

**Comment by SgtBatten** [comment]
Implemented by #172
