### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by tonysystem76** [SgtBatten/HA_blueprints#175]
### Describe the problem you are having or the outcome you are trying to achieve.

I am trying to find  a way to change where the snapshots are saved.

### Version

0.12.0.2

### Automation config file

```yaml
I'm just using the blueprint
```

**Comment by SgtBatten** [comment]
I'll be honest. I've got no idea where the snapshots are saved as I just use the default. 

This automation doesn't have anything to do with it. It's a frigate question.
