### ISSUE TITLE
[Feature Request]: Notification Group Editable

### ISSUE THREAD

**Issue by nicksterz** [SgtBatten/HA_blueprints#182]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to customize the notification group so that I can categorize my notifications based on a priority versus default by the camera name

**Describe the solution you'd like**
Have a text box default with the original '{{ camera }}-frigate-notification' which can be edited.

**Comment by SgtBatten** [comment]
This is available in the beta currently
