### ISSUE TITLE
Notifications if I'm not present OR I'm present during night time hours.

### ISSUE THREAD

**Issue by tsneidin** [SgtBatten/HA_blueprints#194]
I want notifications if I'm not present OR I'm present  and during the hours I specify (night time).

**Comment by SgtBatten** [comment]
Create a template you are happy with using the template editor in home assistant ad paste it into the custom filter field in the beta version of the blueprint. 

It needs to result in true or false.

**Comment by tsneidin** [comment]
Perfect, Thanks.
