### ISSUE TITLE
[Feature Request]: Notify Hass Agent

### ISSUE THREAD

**Issue by patienttruth** [SgtBatten/HA_blueprints#196]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to recieve my frigate notifications with HASS.Agent on my PC

https://hassagent.readthedocs.io/en/latest/notifications/notification-usage-and-examples/

**Describe the solution you'd like**
Either allow the HASS.Agent notification type as a separate target device type, or somehow integrate it as an option to target.

**Describe alternatives you've considered**
- Modifying the blueprint device filters to allow this.
- Creating a `hass_agent` group.

**Additional context**

I did create a `hass_agent` group. I was able to recieve the notification, but had to add my base url to get the photos to work. I'm still having trouble getting the actionable notification buttons to work. They show up, but appear to do nothing. Reading through the HASS.Agent docs I'm thinking the actions generated by the blueprint must be Android / IOS specific and not interact with the way HASS.Agent is set up to work.

https://hassagent.readthedocs.io/en/latest/notifications/new/notification-actionable/

**Comment by patienttruth** [comment]
Perhaps this is breaking on the HASS.Agent side.
https://lab02research.youtrack.cloud/issue/hassagent-93/Notifications-make-actionable

It looks like something happened with release 2022.13.0 regarding notifications per the note on that issue, however I don't see URLs mentioned in the release notes.
https://github.com/LAB02-Research/HASS.Agent/releases/tag/2022.13.0

**Comment by patienttruth** [comment]
I figured out that you need to add a browser in the HASS.Agent settings. However while that test button opens a browser, I'm still not getting the browser to open from the notification.

![1b8779604cff3958a4b98072dc2c9e28e7b144fe_2_690x484](https://github.com/SgtBatten/HA_blueprints/assets/105557996/b6e412af-fe99-491f-ab57-2bf6cc6d30c8)

https://community.home-assistant.io/t/hass-agent-windows-client-to-receive-notifications-use-commands-sensors-quick-actions-and-more/369094/524?u=cake1468

**Comment by patienttruth** [comment]
I learned there is a fork of Hass.Agent that is being developed while the original dev is unavailable to maintain the original project. Long term they hope to merge back into the original.

That said, they have added support for "android type" notifications, so I've mostly got mine working how I desired with this blueprint.

You do have to set a browser in the HASS.Agent settings.

https://hass-agent.io/latest/

**Comment by patienttruth** [comment]
I missed issue #119 when I made this issue, but it's related.

**Comment by SgtBatten** [comment]
Thanks for the update. Sorry for the slack of replies. I didn't have time to dig into it yet. Your updates have been appreciated.

**Comment by patienttruth** [comment]
You're welcome @SgtBatten. Thanks for making and keeping this project moving forward. Cheers.
