### ISSUE TITLE
[Issue]: Cannot leave notify_device empty to put notify_group instead

### ISSUE THREAD

**Issue by felipecrs** [SgtBatten/HA_blueprints#202]
### Description

https://github.com/SgtBatten/HA_blueprints/assets/29582865/54dabd66-1429-4d3d-8849-221d9c8555d6

### Version

Latest Stable

### Automation Config

```yaml
N/A
```

**Comment by felipecrs** [comment]
I think I see now "This will be ignored in that case but is still required."

**Comment by ezcGman** [comment]
I just stumbled over the same issue. Should still fix the post here saying "[...] you may send the notification to multiple devices by **leaving “Mobile Device” blank** and instead send to a notification group [...]", @SgtBatten 

Thx!!
