### ISSUE TITLE
[Feature Request]: Vacation Mode

### ISSUE THREAD

**Issue by NasKar2** [SgtBatten/HA_blueprints#207]
**Describe what you are trying to accomplish and why in non technical terms**
I want to set a toggle for vacation mode that would prevent frigate notification when on vacation in a different time zone. 

**Describe the solution you'd like**
Turn off notifications if the vacation mode toggle is on. 

**Additional context**
Would like to use the toggle in other automation so I would have one place to set the vacation mode.

**Comment by kdelios** [comment]
Just disable the notification when on vacation

**Comment by NasKar2** [comment]
I would prefer to not have to disable multiple automations manually.  Would be best to set an input boolean to disable or delay the notifications by a certain number of hours to prevent getting woken up by a package being delivered etc.
