### ISSUE TITLE
[Feature Request]: Multiple Presence Filter

### ISSUE THREAD

**Issue by Evolver13** [SgtBatten/HA_blueprints#211]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set multiply Presence Filter so that I can shut off notification if everybody is at home 

**Describe the solution you'd like**
Please add Multiple Entities like it is for Zones

**Comment by SgtBatten** [comment]
If group behavious is not what you want you could make a template and use the custom filter to achieve this.

**Comment by Evolver13** [comment]
What do you mean with group behaviours?

Right now I could only find one point so select a presence filter and there I only can add one person instead of multiple people

**Comment by SgtBatten** [comment]
yes but if you created a group within home assistant it should also show up there.
