### ISSUE TITLE
[Feature Request]: Sticky Notification option for IOS

### ISSUE THREAD

**Issue by reesion** [SgtBatten/HA_blueprints#22]
**Describe what you are trying to accomplish and why in non technical terms**
Sticky notification - notification disappears when clicked. If viewing snapshot the notification disappears and unable to go back and view clip. 

**Describe the solution you'd like**
configurable sticky notifications

**Comment by SgtBatten** [comment]
Hi @reesion 

Sticky notifications are already in the beta. 

I find without sticky notification the notification only disappears if I tap the notification or use button 3. Button 2 and button 1 usually don't cause it to close. Let me know how you go

**Comment by reesion** [comment]
Hi @SgtBatten ,

Thank you for the response. I have had a look at the beta settings and it seems that the sticky option is for Android? Does it work for iOS as well?

**Comment by SgtBatten** [comment]
No, there is no equivalent option for IOS I can see in the home assistant documentation.
