### ISSUE TITLE
[Config Support]: Conditional alerts based on time and camera location

### ISSUE THREAD

**Issue by Razielza** [SgtBatten/HA_blueprints#225]
### Describe the problem you are having or the outcome you are trying to achieve.

I tried this blueprint and it works fantastic, however I find it a bit harder to identify how to properly customize it due to being a lot more familiar with NodeRed.  In NodeRed I've been using a couple of conditions to filter certain states, which I am struggling to get working with the blueprint. Would this be possible to configure with the blueprint or do I have to create an automation for every single use case?

My NodeRed Flow which does the following

Between 00:00 and 06:30 it alerts for a person detected on all cameras, outside of that time it only alerts on the "inside" cameras if both me or my wife is not home. 
If I am home and my PC is on, it alerts on my PC, if not it alerts on my phone, unless it is between 23:00 and 07:00, then it alerts on both. 

Any idea if something like this is possible with this blueprint? 

![image](https://github.com/SgtBatten/HA_blueprints/assets/8158497/4efd1e50-ce14-465b-b679-8d048d045cc8)

### Version

0.12.0.4a

### Automation config

```yaml
NodeRed Flow posted above
```

### Any other information that may be helpful

If I can even just split the cameras to "inside" and "Outside" for notifications to alert at certain times that could also be helpful if the full flow is not possible

**Comment by Mikescotland** [comment]
Why complicate it?
Just create two or more notifications with different cameras and make an automation in home assistant to switch particular ones on and off according to time. Easy peasy
