### ISSUE TITLE
[Feature Request]: Notification Sound - Android

### ISSUE THREAD

**Issue by superdong69** [SgtBatten/HA_blueprints#227]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use custom notification sounds on android devices, like IOS can.

**Comment by SgtBatten** [comment]
its been a long time sinc ei looked at this but you should be able to set custom sounds on the device itself based on the notification channel you define

**Comment by superdong69** [comment]
Unfortunately you can't.  I mean,  you can,  but not for each different notification.  For example,  for the front walk notification I want the sound to say,  front walk detection,  versus rear garden etc.

**Comment by SgtBatten** [comment]
Try the new TTS options added in #221

**Comment by AriaGen** [comment]
Set up more than one automation for each camera/zone you wish different and set them with a different channel on each automation (don't use critical), then go to (Samsung) Settings > Notifications > App Notifications > Find/Search for Home Assistant > Notification Categories and you'll be able to change and define settings in there. Make sure to trigger the notification first as it'll only appear on the list after the first notification.
