### ISSUE TITLE
[Feature Request]: Trigger not by motion, but solely by a binary sensor - Reolink Doorbell - Visitor

### ISSUE THREAD

**Issue by bobmarley2021** [SgtBatten/HA_blueprints#228]
**Describe what you are trying to accomplish and why in non technical terms**

I use this for a Reolink Doorbell. The problem I have is that I would also like to use it to create a separate automation when someone presses the doorbell button. On Reolink Doorbells, this is indicated with the "visitor" binary sensor, which is either `on` or `off`. For example:

`binary_sensor.reolink_doorbell_visitor`

It would be great to have all the awesome features of this great blueprint, but with the option for the trigger simply being when the binary sensor is set to on, regardless of motion.

**Describe the solution you'd like**

For the blue print to be adapted to allow triggering only by a binary sensor, regardless of motion.

**Describe alternatives you've considered**

I have tried using the "State Filter Entity", but it's not perfect. If someone presses the bell and is out of view (ie. a child or someone messing around) it doesn't fire the automation. I have found even when stood in front of the doorbell, pressing it still does sometimes not fire the automation. I am assuming this is a motion detection issue with frigate perhaps.

**Additional context**

Not really, just firing with the binary sensor would do it. :) Regardless of motion detection and how good/accurate it is, one thing than never fails is the binary sensor when someone presses the bell.

**Comment by bobmarley2021** [comment]
Wow...not even a comment after all this time?

**Comment by SgtBatten** [comment]
i have a reolink doorbell myself, the reason its got no comment is because it's not possible to fire this blueprint with anything other than a frigate event. there is too much information required from the frigate mqtt message for anything else to work.

**Comment by bobmarley2021** [comment]
Ok, well thanks for providing an explanation. If, in the future, you should happen to create a blueprint with this functionality that does work with the Reolink door bell without relying on Frigate, that would be awesome.

Cheers, 

Bob
