### ISSUE TITLE
Multi-Zone - From and To

### ISSUE THREAD

**Issue by AriaGen** [SgtBatten/HA_blueprints#234]
I like the idea of the multi-zone filter, if I understand it correctly, the object being tracked needs to enter both zones for the notification to trigger. I would, like to, have the ability to only be notified if the objects enter zones in a specific order. 

I'm not sure if this would be even possible, I don't know how frigate handles zones.

The automation would need to trigger at the moment that the first zone if entered, then wait to see if there is a update with the second zone. 

The idea being, I want to be notified if someone enters my driveway from the street, but not when someone moves from my driveway to the street. 

Presently I do it with whether the door has been opened within a period of time.

**Comment by AriaGen** [comment]
Upon closer looking through the project, Looks like it's already being implanted  👍 🥇

**Comment by andilee7** [comment]
nevermind. found it in the beta blueprint
