### ISSUE TITLE
[Feature Request]: Mute notification predefined timer

### ISSUE THREAD

**Issue by PovilasID** [SgtBatten/HA_blueprints#24]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set for how long notifications are muted.

**Describe the solution you'd like**
There are two options how to implement it that can both co-exist:
a) In notification action selection list add more options with predefined notification muting times (10 minutes; 1 hour; 3 hours; 6 hours... etc.)
b) In notification action selection list add `Mute for...` and when it is elected a dialog pops up with a list of options.

**Describe alternatives you've considered**
Training AI to learn my face... takes time... needs plugins... later. Presence detection methods are... not consistent. 

**Additional context**
This is functionality that I have seen in "Alfred"  and Android app that turns your smartphone into a security web cam. 
This suspension of of notifications is handy when place is not visited that often  and presence detection is too slow.

**Comment by SgtBatten** [comment]
Are you wanting to have multiple actions buttons with different mute times?

**Comment by PovilasID** [comment]
> Are you wanting to have multiple actions buttons with different mute times?

In the options for quick actions for notifications there three options one of them being "mute" I am not sure how long does it mute for.
Options to change that would be nice.

**Comment by SgtBatten** [comment]
> I am not sure how long does it mute for.
> Options to change that would be nice.

There is a slider called silence timer which sets how long it stops new events being sent

**Comment by PovilasID** [comment]
I though it was for something else because I would keep getting notifications even after I muted the cammera.

**Comment by SgtBatten** [comment]
Only for the existing events. It actually disables the automation so you should easily be able to confirm it has worked by looking at the automation page in HA. It renables after the set time.
