### ISSUE TITLE
[Feature Request]: Allow 12-hour timestamp

### ISSUE THREAD

**Issue by pyrodex** [SgtBatten/HA_blueprints#247]
**Describe what you are trying to accomplish and why in non technical terms**
I love the timestamp in the notification but not all of us live in a 24-hour time model so could you offer an option as a drop down because it would be usable over and over.
**Describe the solution you'd like**
Add 12-hour timestamp to the drop down for notifications along side 24-hour timestamp
**Describe alternatives you've considered**
Modifying the YAML in Home Assistant but it could lead to issues if updating the blueprint in the future.
**Additional context**
N/A

**Comment by SgtBatten** [comment]
These are fully configurable fields, you just need to convert to 12 hour instead, I dont have an example on hand but you can edit the existing field however you like. the ones showing are just some examples.
