### ISSUE TITLE
[Config Support]: Filter by face matches

### ISSUE THREAD

**Issue by norimicry** [SgtBatten/HA_blueprints#257]
### Describe the problem you are having or the outcome you are trying to achieve.

I would like to NOT receive notifications based on certain facial matches from Double Take. How would I use the custom filter to do this if possible?

### Version

0.12.0.4a

### Automation config

```yaml
alias:%20Frigate%20Notifications%20(Doorbell)%0Adescription%3A%20%22%22%0Ause_blueprint%3A%0A%20%20path%3A%20SgtBatten/Stable.yaml%0A%20%20input:%0A%20%20%20%20camera:%20camera.doorbell%0A%20%20%20%20notify_group:%20notify_all%0A%20%20%20%20message:%20%22%7B%7B%20label%20%7D%7D%20detected%20-%20%7B%7B%20camera_name%20%7D%7D%22%0A%20%20%20%20tap_action:%20%3E-%0A%20%20%20%20%20%20%7B%7Bbase_url%7D%7D/api/camera_proxy_stream/camera.%7B%7Btrigger.payload_json%5B'after'%5D%5B'camera'%5D%0A%20%20%20%20%20%20%7C%20lower%20%7C%20replace('-','_')%7D%7D?token=%7B%7Bstate_attr(%20'camera.'%20~%20camera,%0A%20%20%20%20%20%20'access_token')%7D%7D%0A%20%20%20%20button_1:%20View%20Stream%0A%20%20%20%20url_1:%20%3E-%0A%20%20%20%20%20%20%7B%7Bbase_url%7D%7D/api/camera_proxy_stream/camera.%7B%7Btrigger.payload_json%5B'after'%5D%5B'camera'%5D%0A%20%20%20%20%20%20%7C%20lower%20%7C%20replace('-','_')%7D%7D?token=%7B%7Bstate_attr(%20'camera.'%20~%20camera,%0A%20%20%20%20%20%20'access_token')%7D%7D%0A%20%20%20%20notify_device:%2059c58e22faf9fd421b1a408c2a7d1448%0A%20%20%20%20zone_filter:%20true%0A%20%20%20%20zones:%0A%20%20%20%20%20%20-%20doorstep%0A%20%20%20%20labels:%0A%20%20%20%20%20%20-%20person%0A%20%20%20%20%20%20-%20package
```

### Any other information that may be helpful

I have Double Take and CompreFace already set up and configured.

**Comment by SgtBatten** [comment]
The variable you need to test against would be {{event['after']['sub_label'][0]}} for the first match, or {{event['after']['sub_label']}} for the list of matches.

**Comment by markmghali** [comment]
> The variable you need to test against would be {{event['after']['sub_label'][0]}} for the first match, or {{event['after']['sub_label']}} for the list of matches.

Could you give me a full a example? I am trying to work out the syntax. I want to be notified on unknown faces only. 

Thank you this Blueprint is absolutely awesome! thank you for all the hard work

**Comment by SgtBatten** [comment]
The trouble you will face is that faces can start unknown and become known, but you already have been notified. 

I think something like this might work

{{event['after']['sub_label']|list|length <1}}

**Comment by markmghali** [comment]
Thank you! So it would go like this in the filter field? I did also try using the unknown entity from double-take in home assistant but not sure if it is working properly 

![image](https://github.com/user-attachments/assets/df941544-abe0-422b-b058-ff75c504fe2f)

**Comment by SgtBatten** [comment]
I think that should work
