### ISSUE TITLE
[Issue]: importing gives `unknown error`

### ISSUE THREAD

**Issue by sophof** [SgtBatten/HA_blueprints#260]
### Description

I'm trying to try out the blueprint, but trying out the button gives an `unknown error` once I get to my home assistant instance. It works fine on other blueprints (tried a random one) and there's no error in the log sadly.

It is the same for both stable and beta.

### Version

0.12.0.4

### Automation Config

```yaml
NA
```

### Frigate Config

```yaml
NA
```

**Comment by UKHarj** [comment]
I having same issue on version. When trying to access the blueprint I get an unknown error message

**Comment by SgtBatten** [comment]
This may be the same as #254 

Can you link me to the place where you are clicking the button so I can test and verify.

**Comment by UKHarj** [comment]
Hi the link is here: https://github.com/SgtBatten/HA_blueprints

**Comment by dardy1** [comment]
I'm having the same issue when trying to import the blueprint.  I'm clicking the button at https://github.com/SgtBatten/HA_blueprints

Looking at the logs while I do this, I see these errors:

2024-08-15 21:18:10.921 ERROR (MainThread) [homeassistant.util.yaml.loader] mapping values are not allowed here
  in "", line 122, column 42:
     ... GitHub - SgtBatten/HA_blueprints: Somewhere to store automation  ... 
                                         ^
2024-08-15 21:18:10.921 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139839551762304] Error handling message: mapping values are not allowed here
  in "", line 122, column 42:
     ... GitHub - SgtBatten/HA_blueprints: Somewhere to store automation  ...

**Comment by SgtBatten** [comment]
I'm not havng the issue. Can you show the whole error in your log

**Comment by UKHarj** [comment]
I have manually imported the blueprint. However I can't select cameras. I have frigate add on installed and using the new version 0.14

**Comment by SgtBatten** [comment]
frigate integration must be installed incorrectly, or not installed.

**Comment by dardy1** [comment]
> I'm not havng the issue. Can you show the whole error in your log

Sorry, I don't have the logs anymore.  When I try to click the install blueprint button, I am still getting an An unknown error occurred.

Is there a way I can install it manually?  Are the steps below correct:

1. Download the May 28th Source Code.
2. Create a folder under homeassistant/blueprints/automation (does it matter what I call this folder), ie HA-blueprints?
3. Upload the yaml file from the downloaded source code.  Is there anything else other than the yaml file I need to put in the folder?  What do I name the yaml file?
4. Do I need to add any lines to my configuration.yaml file or the automations.yaml?  I am not in yaml mode, so I don't typically need to manually edit this file.

**Comment by SgtBatten** [comment]
No that's way over complicating it. 

Everyone else is saying if you click import on the blueprint page in HA and manually paste the url to the blueprint it works. 

But if you need to manually install it, go to the file if the one you want, copy the text and paste it into a new text file you make in the blueprint folder inside HA.

**Comment by dardy1** [comment]
> No that's way over complicating it.
> 
> Everyone else is saying if you click import on the blueprint page in HA and manually paste the url to the blueprint it works.
> 
> But if you need to manually install it, go to the file if the one you want, copy the text and paste it into a new text file you make in the blueprint folder inside HA.

Pasting URL didn't work for me for some reason, but I was able to get it working.  Thanks for the help.

**Comment by SgtBatten** [comment]
Can anyone try the new links on the readme (main page of this repository)

**Comment by SgtBatten** [comment]
Anyone getting the error please check the home assistant log afterwards and post the full error.

**Comment by lyj0309** [comment]
no log ,just `An unknown error occurred`

**Comment by TheRealFalseReality** [comment]
> Can anyone try the new links on the readme (main page of this repository)

on my fork, I removed the spaces in Frigate Camera Notifications -> Frigate_Camera_Notifications and created a HA link using the link button creator and it seemed to have worked properly.

**Comment by SgtBatten** [comment]
Yeah I've long wondered if that is problematic. But I've had 25000 clicks on the home assistant forum and only problems recently. 

It also works fine for me still as is and I'm not sure if that's because I already have it downloaded and updating doesn't have the same issue

**Comment by SgtBatten** [comment]
Okay i;ve renamed the folder,

@lyj0309 can you please try the link on the main page of this repository again.

**Comment by SgtBatten** [comment]
Thanks

**Comment by TheRealFalseReality** [comment]
Working now too. 
So strange how things work sometime, but not for all. And strange that it would work one day, then break the next!

**Comment by sophof** [comment]
Working for me as well, thanks! (sorry, couldn't be more active until now.)

**Comment by SgtBatten** [comment]
Thanks all

**Comment by lyj0309** [comment]
Working now

**Comment by mostlychris** [comment]
...and working for me. Thanks for fixing it! Also the blueprint is awesome.
