### ISSUE TITLE
[Feature Request]:   multiple cameras 

### ISSUE THREAD

**Issue by kiloptero** [SgtBatten/HA_blueprints#261]
I’ve been integrating multiple cameras into my setup, and I think it would be great if we could handle more than one camera at a time without having to create separate automations for each.

For those of us with several cameras, creating 6 or more automations for every camera can get pretty overwhelming. It would be awesome if there was a more efficient way to manage them all in a single automation or using some kind of template.

Just wanted to share this idea and see if anyone else feels the same or has any suggestions. Thanks again for the fantastic work!

**Comment by SgtBatten** [comment]
#26 Its been requested before and if i ever get the time i will see what we can do.
