### ISSUE TITLE
[Feature Request]: Support doorbell action trigger

### ISSUE THREAD

**Issue by JoshuaSeidel** [SgtBatten/HA_blueprints#270]
**Describe what you are trying to accomplish and why in non technical terms**
Frigate notification like this when doorbell is rung

**Describe the solution you'd like**
I want to be able to trigger this notification based on a bianary sensor getting triggered e.g a doorbell getting rung. and not anything else

**Describe alternatives you've considered**
forking and rebuilding

**Additional context**

**Comment by SgtBatten** [comment]
This blueprint needs mqtt input from frigate. it's not set up for other triggers. A far simpler automation would be possible.
