### ISSUE TITLE
[Feature Request]: Notification links inside of HA

### ISSUE THREAD

**Issue by JoshuaSeidel** [SgtBatten/HA_blueprints#274]
I want to be able to operate completely in HA, when notifications from HA come in, I want the video to open within HA on the frigate window.

The Scrypted integration with HA triggers home assistant notifications, when those notifications are clicked on, the. Go back into home assistant and open the Scrypted section and show the clip there. This is ideal, I don't want to have a bunch of open tabs in my browser throughout the day to view the videos

URI: Lovelace/view/0 would go back into home assistant and go to that view. Can't we have it go into frigate proxy and a page within that? 

Hopefully these links will show in a way how it's being done
https://github.com/koush/ha_scrypted

https://github.com/scryptedapp/homeassistant/blob/main/src/notify.ts

**Comment by SgtBatten** [comment]
All the URLs are customisable. Write whatever you want. 

Going to a specific camera inside frigate is not possible. The url isn't explicit. 

If you make your own dashboard page for each cam you could.
