### ISSUE TITLE
Thumbnails and dynamic names

### ISSUE THREAD

**Issue by blueharford** [SgtBatten/HA_blueprints#280]
### Describe the problem you are having or the outcome you are trying to achieve.

Recently snapshots stopped showing. I see that in frigate home assistant integration that all images show as “person” “dog” “package” “cat” etc as the actual entity name. Not snapshot. Could that be why?

also not sure but when I was standing infront of the doorbell after a few seconds the notification changed from “a person” to “Joshua” but as soon as I moved, the notification changed back. Can I make it so once it updates with the recognition it stays on that specific notification?

### Version

Latest

### Automation config

```yaml
alias:%20%22Front%20door%20notification%20%22%0Adescription%3A%20%22%22%0Ause_blueprint%3A%0A%20%20path%3A%20SgtBatten/Stable.yaml%0A%20%20input:%0A%20%20%20%20camera:%20camera.doorbell%0A%20%20%20%20notify_device:%200fce7692dbc619c242f66452044447da%0A%20%20%20%20notify_group:%20notify.seidels%0A%20%20%20%20base_url:%20https://ha.joshuaseidel.com%0A%20%20%20%20title:%20Home%20Alert%0A%20%20%20%20alert_once:%20true%0A%20%20%20%20attachment:%20snapshot.jpg?bbox=1&crop=1%0A%20%20%20%20video:%20%3E-%0A%20%20%20%20%20%20%7B%7Bbase_url%7D%7D/api/frigate%7B%7Bclient_id%7D%7D/notifications/%7B%7Bid%7D%7D/%7B%7Bcamera%7D%7D/clip.mp4%0A%20%20%20%20icon:%20%3E-%0A%20%20%20%20%20%20mdi:%7B%7B'account-outline'%20if%20label%20==%20'Person'%20else%20'dog'%20if%20label%20==%20'Dog'%0A%20%20%20%20%20%20else%20'cat'%20if%20label%20==%20'Cat'%20else%20'car'%20if%20label%20==%20'Car'%20else%0A%20%20%20%20%20%20'home-assistant'%7D%7D%0A%20%20%20%20ios_live_view:%20camera.doorbell%0A%20%20%20%20zone_filter:%20true%0A%20%20%20%20zones:%0A%20%20%20%20%20%20-%20porch%0A%20%20%20%20disable_times:%0A%20%20%20%20%20%20-%20%2222%22%0A%20%20%20%20%20%20-%20%2223%22%0A%20%20%20%20sound:%20US-EN-Alexa-Motion-At-Front-Door.wav%0A%20%20%20%20labels:%0A%20%20%20%20%20%20-%20person%0A%20%20%20%20%20%20-%20package%0A%20%20%20%20update_thumbnail:%20true%0A
```

**Comment by blueharford** [comment]
`Frigate Notification DEBUG (in loop): Send Notification: False Info: sublabel: None, image: "https://ha.joshuaseidel.com/api/frigate/notifications/1726181029.091877-h0bkyq/snapshot.jpg?bbox=1&crop=1" Title: Home Alert message: A Person was detected on the Doorbell camera. iOS sound: disabled by alert once, Android Sound: disabled by alert once, iOS url: /api/frigate/notifications/1726181029.091877-h0bkyq/doorbell/clip.mp4 video: "https://ha.joshuaseidel.com/api/frigate/notifications/1726181029.091877-h0bkyq/doorbell/clip.mp4" critical: False, Triggers: New Snapshot: False Presence Changed: False, Stationary Moved: False, Entered Zones Changed: False, sublabel changed: False, Conditions: Loitering: 0 or Filters: Zones: Zone Filter Enabled: True, Multi Zone Enabled: False, Required Zones: ['porch'], Last Zones: ['porch'], Entered zones: 1 - ['porch'], TEST: PASS, Object Filter: Input: ['person', 'package'], TEST: PASS, Presence entity (not home): Entity: , TEST: PASS, Time Filter: Disabled times: ['22', '23'], TEST: PASS State Filter: state filter toggle on: False, state filter entity: , required states: [], TEST: PASS, Custom Filter: PASS, triggered by automation Front door notification mqtt topic frigate/events

**Comment by blueharford** [comment]
The snapshot or clip comes through on my watch but not on my phone

**Comment by SgtBatten** [comment]
please fill out the inssue template properly. I need the version number and the automation config properly formatted. the instructions are in the template for doing this. 

Regarding the snapshot issue i see you have another issue open #276

**Comment by gomble** [comment]
I have the same problem.
On my watch i can see the thumbnail but not on my iphone 16 pro max

**Comment by SgtBatten** [comment]
> I have the same problem.

too many variables, open a new issue please. But the answer is probably the same as others, IOS doesnt like the video tag in the blueprint right now

**Comment by gomble** [comment]
> > I have the same problem.
> 
> too many variables, open a new issue please. But the answer is probably the same as others, IOS doesnt like the video tag in the blueprint right now

i dont have the video tag activated:
`alias: Frigate EingangPTZ
description: ""
use_blueprint:
  path: SgtBatten/Stable.yaml
  input:
    camera: camera.eingangptz
    notify_group: family_ios
    base_url: https://----:8123
    message: "{{ label }} detected - {{ camera_name }}"
    alert_once: true
    icon: >-
      mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
      else 'cat' if label == 'Cat' else 'car' if label == 'Car' else
      'home-assistant'}}
    zone_filter: false
    zones: []
    button_2: View Stream
    url_2: >-
      {{base_url}}/api/camera_proxy_stream/camera.{{trigger.payload_json['after']['camera'].lower()}}?token={{state_attr(
      'camera.' ~ camera, 'access_token')}}
    tap_action: /ccab4aaf_frigate-proxy/dashboard
    cooldown: 70
    title: 📷
    disable_times:
      - "0"
      - "2"
      - "3"
      - "4"
      - "1"
      - "5"
      - "6"
    notify_device: a30f870365ccf7b8e87afec2f00e096e
    attachment: thumbnail.jpg
    update_thumbnail: true
`
![image](https://github.com/user-attachments/assets/cc9783c0-f2f3-4edb-a0b5-5c21794eaeba)

It worked until iOS 18

**Comment by SgtBatten** [comment]
> i dont have the video tag activated:

yes but the blueprint/automation does and  still sends it empty.

**Comment by gomble** [comment]
> > i dont have the video tag activated:
> 
> 
> 
> yes but the blueprint/automation does and  still sends it empty. 

I found out if you activate local push in the homeassistant ios app i dont get a thumbnail if i deactivate it, it works again.
