### ISSUE TITLE
[Config Support]: Frigate 0.14 Branch vs 0.12 Main Branch

### ISSUE THREAD

**Issue by Amadou91** [SgtBatten/HA_blueprints#301]
### Describe the problem you are having or the outcome you are trying to achieve.

Hello,

I have a general question regarding the use of Frigate notification branches.

With the release of Frigate 0.14, I noticed that work has resumed on improving notifications—thank you for that! However, I'm a bit confused about whether I should be using the main branch (0.12) or the Frigate 0.14 Beta branch.

I've observed that some features are present in the Frigate 0.14 Beta branch but not in the main branch, and vice versa. For instance:

Frigate 0.14:

- Using frigate/reviews seems to generate the exact number of notifications I expect. I believe this is related to how frequently the frigate/reviews topic is updated compared to the frigate/events topic. **This could be a misunderstanding on my part, but frigate/reviews gives me the exact behavior I want**

- I can select between Reviews and Detections. _(this is minor)_

- However, Frigate 0.14 is 29 commits behind the main branch, so I know there are many quality-of-life and user-flow improvements in the main branch.

I'm seeking some direction on the best path forward. Ultimately, I prefer using the frigate/reviews topic, but when I tried the main branch (0.12) and changed my topic from frigate/events to frigate/reviews, I encountered various issues. As a result, I reverted to the Frigate 0.14 Beta branch.

Could you please advise on whether I should continue using the Frigate 0.14 Beta branch or switch to the main branch? Any guidance would be appreciated.

Thank you!

### Version

0.12.0.4p

### Automation config

```yaml
N/A
```

**Comment by SgtBatten** [comment]
main branch only works with frigate/events. the 0.14 branch only works with reviews. reviews topic is how it will be going forward once i eventually publish 0.14 to main. 

I can try to bring some more recent main branch updates to the 0.14 brnach if i get time.  Lack of feedback is the primary reason progress is slow.

**Comment by nottledim** [comment]
My notifications have stopped working too. I think because I upgraded to 0.14.  The android notification just says "this page isnt working".

I'm looking forward to getting that working again :-)

**Comment by SgtBatten** [comment]
Nothing changed in the API we use from frigate. Upgrading from frigate 0.12 to 0.14 requires no changes to the automation. So whatever you have happening is different.

**Comment by nottledim** [comment]
Yes, you're right.  I downgraded to old version 0.13.2 and it still doesn't work!!  I've done something; I don't know what.  I'm getting http 400 errors when I try to get the clip.  There's a mention of Unable to find notify service for webhook ID in the logs.  

Anyway, sorry to bother you.

**Comment by SgtBatten** [comment]
> Unable to find notify service for webhook ID

I dont know specifically but perhaps your phone needs to be reinstalled with the app. I'd be searching for this error anyway.

**Comment by SgtBatten** [comment]
The endpoint comes from the frigate integration. Maybe reinstall that

**Comment by Amadou91** [comment]
> main branch only works with frigate/events. the 0.14 branch only works with reviews. reviews topic is how it will be going forward once i eventually publish 0.14 to main. 
> 
> 
> 
> I can try to bring some more recent main branch updates to the 0.14 brnach if i get time.  Lack of feedback is the primary reason progress is slow. 
> 
> 

Great to hear about the main branch’s future! If there are any specific areas where additional testing would help, I’m more than happy to assist.

From my end, 0.14 (/reviews) seems to work **exactly** as intended. I _now_ always receive snapshots (whether on or off WiFi), and I’m no longer getting false updates/notifications during an event, which I still encounter with the 0.12 main branch.

I suspect this issue might be tied to how the /events topic updates while an event is in progress. Essentially, in many cases, I receive an event update, but the snapshot shows a **404** error, and if I click on the notification, it just displays JSON saying “No event found.”.

Anyway.. I just use 0.14 😅

**Comment by SgtBatten** [comment]
I've updated my copy of 0.14 with all the main branch improvements. Testing things a bit now

**Comment by hobybrenner** [comment]
I agree, this .14 is working well and I look forward to the update.

**Comment by SgtBatten** [comment]
.14 branch is updated with all major improvements from the main branch. 

Please test it out as much as you can and post feedback in the pull request #216 

Prepping to release it to main branch
