### ISSUE TITLE
[Feature Request]: Use Telegram as the notification platform instead of app notifications

### ISSUE THREAD

**Issue by Ranger2959** [SgtBatten/HA_blueprints#31]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to use telegram to publish notifications instead of only app notifications.

**Describe the solution you'd like**
Use notify.telegram to publish notifications

**Additional context**
I set the notification_group to "notify.telegram" (that I set up) but I only receive a message saying "Motion was detected on the porch camera."

**Comment by SgtBatten** [comment]
Can you please provide a sample of the required format to send all the things we already send. Links to documentation etc

**Comment by Chrisgozd** [comment]
@SgtBatten 

Here is the docs for text: https://www.home-assistant.io/integrations/telegram/#text-message
Photo: https://www.home-assistant.io/integrations/telegram/#photo-support
Video: https://www.home-assistant.io/integrations/telegram/#video-support

**Comment by SgtBatten** [comment]
Please test the version at that link

**Comment by pedromrg** [comment]
> Please test the version at that link

getting: Invalid blueprint: Missing input definition for telegram_group

**Comment by SgtBatten** [comment]
@pedromrg just made some changes. Note you'll need to set the group again as the input key has changed to notify_telegram_group

**Comment by pedromrg** [comment]
> some changes. Note you'll need to set the group again as the input key has changed to notify_telegram_group

Same error: Invalid blueprint: Missing input definition for notify_telegram_group

-----

Another thing I forgot to mention:

selector:
        entity:
          integration: frigate
          domain: camera
          device_class: camera - ERROR here : 

Value is not accepted. Valid values: "apparent_power", "aqi", "atmospheric_pressure", "awning", "battery", "battery_charging", "blind", "carbon_dioxide", "carbon_monoxide", "cold", "connectivity", "current", "curtain", "damper", "data_rate", "data_size", "date", "distance", "door", "duration", "energy", "energy_storage", "enum", "frequency", "garage", "garage_door", "gas", "gate", "heat", "humidity", "illuminance", "irradiance", "light", "lock", "moisture", "monetary", "motion", "moving", "nitrogen_dioxide", "nitrogen_monoxide", "nitrous_oxide", "occupancy", "opening", "outlet", "ozone", "plug", "pm1", "pm10", "pm25", "power", "power_factor", "precipitation", "precipitation_intensity", "presence", "pressure", "problem", "reactive_power", "receiver", "running", "safety", "shade", "shutter", "signal_strength", "smoke", "sound", "sound_pressure", "speaker", "sulphur_dioxide", "switch", "tamper", "temperature", "timestamp", "tv", "update", "vibration", "volatile_organic_compounds", "voltage", "volume", "volume_storage", "water", "weight", "wind_speed", "window".yaml-schema: http://schemas.home-assistant.io/blueprint-automation(1)
No quick fixes available

**Comment by SgtBatten** [comment]
@pedromrg hey mate, sorry about that. I was doing it from my phone and missed an e. I think it's good now. 

The second error will always be there. Frigate gives the actual camera entities the device class of camera and it's the only way i can distinguish between things like camera.front and camera.front_person for the camera select input. Home assistant does not consider camera a valid device class, but it still works for the purpose of eliminating all but the real frigate cams from that drop down.

**Comment by pedromrg** [comment]
> @pedromrg hey mate, sorry about that. I was doing it from my phone and missed an e. I think it's good now.
> 
> The second error will always be there. Frigate gives the actual camera entities the device class of camera and it's the only way i can distinguish between things like camera.front and camera.front_person for the camera select input. Home assistant does not consider camera a valid device class, but it still works for the purpose of eliminating all but the real frigate cams from that drop down. I did a pull request a long time ago to add camera as a valid device class and it was rejected. It's only an error in the schema validation. works fine.

Thanks for the explanation! 

Tested, so I have added the name of the group set on my notify. 

Name set on the blueprint test_group

Getting this error when automation is executed:

Stopped because an error was encountered at 27 May 2023 at 00:46:49 (runtime: 0.05 seconds)

Template rendered invalid service: notify.

**Comment by SgtBatten** [comment]
What is the name of the telegram service you are using? From Dev tools, services.

**Comment by pedromrg** [comment]
> What is the name of the telegram service you are using? From Dev tools, services.

notify.test_group 

Tested and working on dev tools

**Comment by SgtBatten** [comment]
Can you send me a screenshot of the trace for one of these errored ones. Like of the picture/image version of the trace on the left.

**Comment by pedromrg** [comment]
Sure, 

<img width="576" alt="image" src="https://github.com/SgtBatten/HA_blueprints/assets/42122508/72d3e7cf-608a-4f39-af84-79c9b6a4d63e">

**Comment by SgtBatten** [comment]
Okay it's trying to do the normal group notify instead of the telegram one. I'll have to fix something.

**Comment by SgtBatten** [comment]
Just made a change to the condition test. Appreciate you trying it out. I don't have telegram setup

**Comment by pedromrg** [comment]
No worries, mate, I can test it out. 
Thanks a lot for the good job.

This is now hitting the correct condition, but it's fetching base_url with https://xxxx.xxx.xx**//** where does this gets the base URL?
If I set it manually in the blueprint, it's working (photo)
-----
Video not working:

service: notify.{{ telegram_target }}
data:
  title: '{{title}}'
  message: '{{message}}'
  data:
    message_tag: '{{ id }}'
    photo:
      - url: >-
          {{base_url}}/api/frigate{{client_id}}/notifications/{{id}}/{{attachment}}.jpg
    video:
      **- url: '{{video}}'**

**Comment by SgtBatten** [comment]
Okay two questions before I change something. 

The IP address when you don't have a baseurl set... Is it you home assistant IP? 

For video, do you have the video input set to clip in the automation config?

**Comment by pedromrg** [comment]
My config:

<img width="624" alt="image" src="https://github.com/SgtBatten/HA_blueprints/assets/42122508/8539400f-0809-4035-a45d-c8fc18bff080">

Confirm. clip is selected in the blueprint.

**Comment by pedromrg** [comment]
Just FYI something aI just spotted in HA logs:

Logger: homeassistant.helpers.template
Source: helpers/template.py:237
First occurred: 20:53:56 (2 occurrences)
Last logged: 20:54:54

Template variable warning: 'video' is undefined when rendering '{{video}}'

**Comment by pedromrg** [comment]
Changes that you made are now outputting the correct value for video URL.

![image](https://github.com/SgtBatten/HA_blueprints/assets/42122508/5ba10789-7b3b-4662-b8ad-27f17a31b1ce)

Video is not coming to Telegram.

I think that to send video we need to use:

service: telegram_bot.send_video
data:
  authentication: digest
  target: -54645643
  file: /config/test.mp4

**Comment by ridizy** [comment]
I'm looking forward to seeing this blueprint working with Telegram.

Just sharing here that I've been using the following to send video to Telegram:

```
- service: notify.telegram_home
  data_template:
    message: (required, but not used)
    data:
      id: "{{ id }}"
      timeout: 100
      video:
      - url: 'https://my.hass.public.host.name/api/frigate/notifications/{{ id }}/clip.mp4'
        caption: "my caption"
```

And here is my notify.telegram_home confirguraton:
```
- name: Telegram_home
  platform: telegram
  chat_id: !secret telegram_home_group
```

Thank you for working on this

**Comment by SgtBatten** [comment]
Yeah I think one issue with my current version is you  can't do pictures and videos at the same time. 

I reversed the order yesterday to see if that might help but haven't tested yet.

**Comment by pedromrg** [comment]
Just did a quick test, same behaviour.

My toughts, maybe this is sending the video but the video is not ready yet so there no file to be sent.... hence nothing arrives.

maybe we need a delay ?!

**Comment by laban85** [comment]
Thanks for putting this together! Telegram notification works for me with thumbnail.

**Comment by SgtBatten** [comment]
> If I send photo + video it just sends the photo indepent from the order.

Thanks, it must just be how telegram does it's thing. might have to make it a choice by the user, e/g if video is not set to none , no photo is sent.

**Comment by joopdo** [comment]
Wonderful, thank you! I was going to make a ticket to get Signal (https://www.home-assistant.io/integrations/signal_messenger/) support, but the above will do fine.

**Comment by SgtBatten** [comment]
> I got it to work in no time!

Are you saying signal worked with the blueprint or you had to make changes?

**Comment by SgtBatten** [comment]
@Ranger2959 can yuu try the latest version in the telegram branch please

**Comment by xekil** [comment]
> @Ranger2959 can yuu try the latest version in the telegram branch please

Good morning,

I tested this beta version and it does not work, I do not receive any notification from telegram.
My notification service is: **notify.telegram**, I fill in **telegram**

The origional version of the blueprint works with home assistant app notifications but I am using telegram.

Thanks in advance


```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:855
Integration: Telegram bot ([documentation](https://www.home-assistant.io/integrations/telegram_bot), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+telegram_bot%22))
First occurred: 13:28:07 (1 occurrences)
Last logged: 13:28:07

Can't send file with kwargs: {'title': 'Person', 'message': 'Person, 'message_tag': '1991551296.711749-qzi972', 'url': '/api/frigate/frigate/notifications//snapshot.jpg', 'caption': 'Person'}

```
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:240
First occurred: 13:28:07 (1 occurrences)
Last logged: 13:28:07

Template variable warning: 'id' is undefined when rendering '/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
```
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:761
Integration: Telegram bot ([documentation](https://www.home-assistant.io/integrations/telegram_bot), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+telegram_bot%22))
First occurred: 13:28:07 (1 occurrences)
Last logged: 13:28:07

Can't load data into ByteIO: Invalid URL '/api/frigate/frigate/notifications//snapshot.jpg': No scheme supplied. Perhaps you meant https:///api/frigate/frigate/notifications//snapshot.jpg?
```

**Comment by SgtBatten** [comment]
The first error might be something but the last two look like you tried to run it manually?

**Comment by xekil** [comment]
I did not perform any manual execution.  I have these three errors at each trigger following the detection of a presence

**Comment by SgtBatten** [comment]
Gotta get some sleep but i've added a baseurl back in (untested). hopefully resolves most of it.

**Comment by xekil** [comment]
Thank you and good night, rest well.

**Comment by xekil** [comment]
There is an improvement in the logs but still errors:

For information, I use the Addon Frigate Proxy and the Bleuprint Telegram does not seem to take it into account unlike the original Blueprint because I receive images and videos with the Bleuprint Original. A lead can be...

```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:855
Integration: Telegram bot (documentation, issues)
First occurred: 14:53:13 (1 occurrences)
Last logged: 14:53:13

Can't send file with kwargs: {'title': 'Person', 'message': 'Person', 'message_tag': '16451336592.654785-imghpm', 'url': 'https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg', 'caption': 'Person'}

```
```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:761
Integration: Telegram bot (documentation, issues)
First occurred: 14:53:13 (6 occurrences)
Last logged: 14:53:13

Status code 404 (retry #2) loading https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg
Status code 404 (retry #3) loading https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg
Status code 404 (retry #4) loading https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg
Status code 404 (retry #5) loading https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg
Can't load data in https://secreturlaccesmyinstanceha.com/api/frigate/frigate/notifications//snapshot.jpg after 5 retries

```

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:240
First occurred: 14:53:13 (1 occurrences)
Last logged: 14:53:13

Template variable warning: 'id' is undefined when rendering '/api/frigate{{client_id}}/notifications/{{id}}/snapshot.jpg'
```

**Comment by SgtBatten** [comment]
It's not processing the event ID which is really odd. 

See the double slash before snapshot.jpg.

**Comment by xekil** [comment]
Yeah that's what I noticed too, strange...

**Comment by SgtBatten** [comment]
Can you turn on debug and post the outputs from that. I apologise for not testing myself right now. Very little time. 

There are instructions here https://github.com/SgtBatten/HA_blueprints/blob/main/Frigate%20Camera%20Notifications/Guide%3A%20Debug%20Option.md

**Comment by SgtBatten** [comment]
Okay thank you. I see the issue with the ID.

**Comment by xekil** [comment]
I just tested the current corrected version [[223acd6]](https://github.com/SgtBatten/HA_blueprints/commit/223acd60847043db0746ba5fa896f451158c9825), there is something new.
I now receive a message and the image, however I no longer receive anything if I choose "clip" or "video for telegram".
And in any case, I don't have the buttons either.

**Comment by SgtBatten** [comment]
Great thank you. 

So we are back to where we were earlier as we don't seems to be able to send a picture and a video only one.

**Comment by xekil** [comment]
I forgot to specify, I do not receive the title of the notification

**Comment by xekil** [comment]
Good morning,

I found a BluePrint that works with the Telegram videos, I receive a photo and 2 minutes later I receive a video (there is a delay in the BluePrint)

Can you adapt it to your blueprint because it cannot be personalized and if you were able to add buttons this would be even better.

**Bleuprint :**
https://pastecode.io/s/7diyrizc
**It is in this video that he shares this BluePrint**
https://www.youtube.com/watch?v=vZdVYfTzBrw

THANKS

**Comment by xekil** [comment]
thank you, Impossible to load the BluePrint
```

SgtBatten/Beta_2.yaml n'a pas pu être chargé
Failed to load blueprint: while parsing a block mapping in "/config/blueprints/automation/SgtBatten/Beta_2.yaml", line 989, column 25 expected <block end>, but found '-' in "/config/blueprints/automation/SgtBatten/Beta_2.yaml", line 990, column 25
```

**Comment by xekil** [comment]
I have changed the indentation and it loads, I will test

**Comment by xekil** [comment]
I did not have to do the right indentation because I cannot record automation

**Comment by xekil** [comment]
thank you, Impossible to load the BluePrint
```

SgtBatten/Beta_2.yaml n'a pas pu être chargé
Failed to load blueprint: while parsing a block mapping in "/config/blueprints/automation/SgtBatten/Beta_2.yaml", line 989, column 25 expected <block end>, but found '-' in "/config/blueprints/automation/SgtBatten/Beta_2.yaml", line 990, column 25
```

I tried to change the indentation but it doesn't seem to be that

**Comment by xekil** [comment]
I just tested with the fix [cc416ee](https://github.com/SgtBatten/HA_blueprints/commit/cc416ee15f9811f77ec010bccb20eacb6188ee74) , the blueprint can load but I don't receive any notification and I have these errors

```
Frigate Notifications (0.12.0.1h) beta 2: Choose at step 1: Frigate Event: Debug: write to Log: choice 1: Error executing script. Error for call_service at pos 1: Error rendering data template: TypeError: can only concatenate str (not "int") to str
Frigate Notifications (0.12.0.1h) beta 2: Choose at step 1: Frigate Event: Error executing script. Error for choose at pos 2: Error rendering data template: TypeError: can only concatenate str (not "int") to str
Frigate Notifications (0.12.0.1h) beta 2: Error executing script. Error for choose at pos 1: Error rendering data template: TypeError: can only concatenate str (not "int") to str

```

`
Error while executing automation automation.frigate_notifications_0_12_0_1h_beta_2: Error rendering data template: TypeError: can only concatenate str (not "int") to str`

**Comment by SgtBatten** [comment]
> I have these errors

I think this was the debug code so I've changed that. 

Please let me know. 

Are you now using a telegram chat ID?

**Comment by xekil** [comment]
I tested, I receive the photo but not the video, I use a Telegram ID  -1006XXXXXXXXX

the beta logs are empty
