### ISSUE TITLE
[Feature Request]: Limit notifications by type (alerts / detection)

### ISSUE THREAD

**Issue by spec8320** [SgtBatten/HA_blueprints#318]
**Describe what you are trying to accomplish and why in non technical terms**
I want to have possibility to limit notifications by filtering incomming messages by severity field so I wont receive detect notifications while Im expecting only alerts. 

**Describe the solution you'd like**

From what I see in documentation (I know that this blueprint use /events topic) in /reviews topic we have field called **severity** it will allow us to filter incomming alerts. Here are docs https://docs.frigate.video/integrations/mqtt/

**Comment by SgtBatten** [comment]
Already implemented in the frigate 0.14 branch
