### ISSUE TITLE
Using reviews mqtt topic

### ISSUE THREAD

**Issue by rykr** [SgtBatten/HA_blueprints#321]
I've seen mentioned of a branch that is using the reviews mqtt topic instead of events.  However, I've not been able to find it.  Anyone got a pointer or input on if it's stable enough to test out.?

**Comment by SgtBatten** [comment]
#216

**Comment by rykr** [comment]
I see that.  When I try to import it I get invalid url.  Is that because I'm using Frigate integration 5.0 and this one is based on 3.0?

**Comment by SgtBatten** [comment]
what url are you importing?
