### ISSUE TITLE
[Feature Request]: Ability to select a motion or binary sensor for the trigger of automation

### ISSUE THREAD

**Issue by StealthyTT** [SgtBatten/HA_blueprints#323]
**Describe what you are trying to accomplish and why in non technical terms**
When using the frigate integration it automatically imports all the zones as sensors. I would like to be able to use one of those zones as the trigger vs the blueprint looking in frigate/events and the consequence of any topic (from what i can tell) coming in seems to trigger the automation rendering cool down pretty much useless. 

**Describe the solution you'd like**
just the ability to set a zone from the camera to trigger

**Describe alternatives you've considered**
I was using this blueprint before, it behaved as i typed above, but overall it lacked in the options that you have

https://community.home-assistant.io/t/camera-send-save-snapshot-to-mobile-device-when-motion-is-detected-with-conditions-now-with-custom-triggers/604156

not sure if there is anyway to implement something like this.  

Thank you for all you are doing.

**Comment by SgtBatten** [comment]
we use all the info from the mqtt message so no, other triggers wont work. 

What I do need to improve on is how the conditions are handled. home assistant does not allow me to use every single condition in the beginning which would resolve the cooldown concerns, but we can put as much as possible up there in the future. 

That being said, I have never had a need to use the cooldown, and it;s even better now with frigate 0.14 using the reviews topic (and i suspect will resolve your issue).

If you use this version in #216 it only triggers when an alert state is determined based on what you define in frigate  for reviews. so regular motion and objects in zones you dont care about no longer trigger events.
