### ISSUE TITLE
[Config Support]: Notification Message Using Zone Variable

### ISSUE THREAD

**Issue by NicholasFlamy** [SgtBatten/HA_blueprints#43]
### Describe the problem you are having or the outcome you are trying to achieve.

I want to have a message as part of the notification that is different based on what zone the object is in.

Example:
A person was detected on the Front Porch. (Likely would look something like this: "A {{ label }} was detected {{ 'on the Front Porch.' if zone = 'frontporcharea'  'in the Front yard.' if zone = 'frontyardarea' }}"

How would I do this?

### Version

0.12.0.1

**Comment by NicholasFlamy** [comment]
If I wanted one more option would I add else again like this?:

A {{ label }} was detected {{ 'on the Front Porch.' if 'frontporcharea' in entered_zones else 'in the Front yard.' if 'frontyardarea' in entered_zones else 'in the driveway.' if 'driveway' in entered_zonres }}

**Comment by SgtBatten** [comment]
Yep

**Comment by NicholasFlamy** [comment]
Thank you.
