### ISSUE TITLE
[Feature Request]: Add Confidence Level Template Value for Notification Text

### ISSUE THREAD

**Issue by binaryn3xus** [SgtBatten/HA_blueprints#54]
**Describe what you are trying to accomplish and why in non technical terms**
I would like to be able to include the confidence level in the notification text.

**Describe the solution you'd like**
I would like to have a template value {{confidence_level}} (or something) that way we can inject the confidence level into the notification somehow.

Examples:  
- `A Person was detected on the Driveway camera (Person: %82)`
- `'Driveway' (Person: %82) was detected and triggered at 9:07:26 AM`
- `Person (%82) detected on Driveway camera`

**Describe alternatives you've considered**
This idea comes from using Blue Iris for a while. I like that I can see how sure it is. I know I can have it overlay-ed in the snapshot but sometimes I don't get the overlay for some reason.

**Comment by SgtBatten** [comment]
Try 
```
{{ event['after']['top_score'] |int(0) }}
```

**Comment by binaryn3xus** [comment]
No luck unfortunately...

`2023-06-26 22:24:48.146 ERROR (MainThread) [homeassistant.components.automation.east_side_camera_detection] Error while executing automation automation.east_side_camera_detection: UndefinedError: 'event' is undefined`

**Comment by SgtBatten** [comment]
Sorry you'll need to be using the beta. Next stable release will have it too.
