### ISSUE TITLE
[Bug]: Cannot load beta blueprint due to yaml linting issue

### ISSUE THREAD

**Issue by irakhlin** [SgtBatten/HA_blueprints#71]
### Description

On line 690 I believe you need to escape the \
camera: "{{ input_camera | regex_replace('^camera\\.|_\\d+$', '') }}"
with the same issue on 705 and 717 as currently the blueprint cannot be loaded

### Version

0.12.0.1i

### Automation Config

```yaml
n/a
```

**Comment by SgtBatten** [comment]
Thanks, I based the update on #63 but i see the issue also. 

I think there are a few ways to solve it. I have escaped the escapes now in beta j.
