### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by MickPBduece** [SgtBatten/HA_blueprints#82]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to group IOS notifications into a group for all cameras instead of by automation.  This would improve notification management for with numerous cameras and other grouped notifications,

**Describe the solution you'd like**
The options to configure a groups as in 
data:
          title: "Smart Home Alerts"
          message: "Something happened at home!"
          data:
            group: "example-notification-group"  

**Describe alternatives you've considered**
I got an impression that yaml can be added to each automation.  If that can accomplish this it would be helpful to have an example
Otherwise - I would consider trying to add the grouping option and create my own blueprint but don't want to continue to need to do that work when others additions came to be.

**Additional context**
This might reduce the requests to have the ability to add multiple cameras in one automation.

Thanks for any consideration or suggestions

**Comment by MickPBduece** [comment]
I took a better look at the blueprint and while I don't yet have my concept working I do see that there is a group already in use that starts with the camera name.  I will be adding a new input for the copy of your blue print and replacing camera with that input. I think though that a better solution would be a more complex selector that calls camera name to continue to be used as the message group but allow it to be adjusted to a name such as "Frigate" to allow consolidation or even a literal  (i. e. Front, side..), the object, etc.

**Comment by SgtBatten** [comment]
Good idea. Try the latest beta.

**Comment by MickPBduece** [comment]
Wow - I Thank you !!

**Comment by MickPBduece** [comment]
Limited testing looks like a big improvement in usability for my case.

**Comment by MickPBduece** [comment]
Couple days later it’s been perfect. Thanks again

**Comment by SgtBatten** [comment]
Cheers
