### ISSUE TITLE
[Feature Request]: Bounding Box enable for all images (Thumbnail/snapshot)

### ISSUE THREAD

**Issue by NonaSuomy** [SgtBatten/HA_blueprints#83]
**Describe what you are trying to accomplish and why in nontechnical terms**
Can you add a control that enables a bounding box to the images `?bbox=1` just need to add this to the end of the image links.

Makes it a lot better when you actually get to see what it detected on etc than just looking at a blank image and not knowing.

Thank you.

**Comment by SgtBatten** [comment]
Happy to implement but curious why you are struggling to tell what triggered it. 

Do you not crop your snapshots? Mine are always zoomed in on the subject.

**Comment by NonaSuomy** [comment]
Ok add &crop=1 as well thank you :D

**Comment by SgtBatten** [comment]
Looking at the docs, these are both queries in the http API which we aren't using. You need to configure frigate to prepare the images the way you desire them to be presented to achieve this.

**Comment by NonaSuomy** [comment]
They work just fine that way added to the end of the image URL as that is how I currently do it.

**Comment by SgtBatten** [comment]
> /api/ which are calls to the http api which yes this is part of.

We use the notification api. we do not use any api listed on that page you linked, but i will proceed with it and see. 

> I already tell frigate to make the bounding box image. You have to then tell it with that url to use it or else it will just give you the standard image.

It's always been controllable via the frigate config afaik. Never used these extra query parameters before.

**Comment by NonaSuomy** [comment]
Let me further test this and get back to you.
Maybe the system is misleading me.

**Comment by SgtBatten** [comment]
> Let me further test this and get back to you.

It probably works fine. I just need to add the parameters as input options. 

Just the frigate docs don't make it clear that it would.

**Comment by SgtBatten** [comment]
Seems to work. Try beta n. Option is in the attachment input.
