### ISSUE TITLE
[Bug]: Text disappearing while trying to type object/label/state on the Automation UI

### ISSUE THREAD

**Issue by SgtBatten** [SgtBatten/HA_blueprints#9]
### Description

Entering valid freetext into the input field in the automation UI is hampered by the input field clearing text every few seconds. You either have to type and hit enter extremely quickly, or edit the automation in yaml mode to be successful.

I have also noted that select selectors with multiple true but custom value false clear, but save a null entry unexpectedly.

**Comment by SgtBatten** [comment]
home-assistant/frontend#16093

**Comment by mr-brains** [comment]
type the text in notepad,copy pastein the template and hit enter works.

**Comment by SgtBatten** [comment]
It should be fixed soon by HA Devs. 

For now you can edit in yaml. Selecting a default option from the list first makes this easy.
